# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='global',
            name='version',
            field=models.CharField(default='0.1', max_length=50),
        ),
        migrations.AddField(
            model_name='schema',
            name='version',
            field=models.CharField(default='0.1', max_length=50),
        ),
        migrations.AddField(
            model_name='userdefined',
            name='version',
            field=models.CharField(default='0.1', max_length=50),
        ),
        migrations.AddField(
            model_name='zone',
            name='version',
            field=models.CharField(default='0.1', max_length=50),
        ),
    ]
