# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0003_warehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
